<?php
  
$i_list_length = (int)readPostVar('list_length');
if($i_list_length <= 0)
 $i_list_length = 10;
setConfigItem(CONFIG_list_length, $i_list_length);
$G_SESSION['config_itemsperpage'] = getConfigItem(CONFIG_list_length);
setConfigItem(CONFIG_editor_type, (int)readPostVar('editor_type'));
$G_SESSION['config_editortype'] = getConfigItem(CONFIG_editor_type);
setConfigItem(CONFIG_store_logs, (int)readPostVar('store_logs'));
$G_SESSION['config_storesessionlogs'] = getConfigItem(CONFIG_store_logs) ? true : false;
 
setConfigItem(CONFIG_can_register, (int)readPostVar('can_register'));
setConfigItem(CONFIG_upon_registration, (int)readPostVar('upon_registration'));
setConfigItem(CONFIG_reg_intro, readPostVar('reg_intro'));
setConfigItem(CONFIG_reg_username, (int)readPostVar('username'));
setConfigItem(CONFIG_reg_password, (int)readPostVar('password'));
setConfigItem(CONFIG_reg_email, (int)readPostVar('email'));
setConfigItem(CONFIG_reg_title, (int)readPostVar('title'));
setConfigItem(CONFIG_reg_firstname, (int)readPostVar('firstname'));
setConfigItem(CONFIG_reg_lastname, (int)readPostVar('lastname'));
setConfigItem(CONFIG_reg_middlename, (int)readPostVar('middlename'));
setConfigItem(CONFIG_reg_address, (int)readPostVar('address'));
setConfigItem(CONFIG_reg_city, (int)readPostVar('city'));
setConfigItem(CONFIG_reg_state, (int)readPostVar('state'));
setConfigItem(CONFIG_reg_zip, (int)readPostVar('zip'));
setConfigItem(CONFIG_reg_country, (int)readPostVar('country'));
setConfigItem(CONFIG_reg_phone, (int)readPostVar('phone'));
setConfigItem(CONFIG_reg_fax, (int)readPostVar('fax'));
setConfigItem(CONFIG_reg_mobile, (int)readPostVar('mobile'));
setConfigItem(CONFIG_reg_pager, (int)readPostVar('pager'));
setConfigItem(CONFIG_reg_ipphone, (int)readPostVar('ipphone'));
setConfigItem(CONFIG_reg_webpage, (int)readPostVar('webpage'));
setConfigItem(CONFIG_reg_icq, (int)readPostVar('icq'));
setConfigItem(CONFIG_reg_msn, (int)readPostVar('msn'));
setConfigItem(CONFIG_reg_aol, (int)readPostVar('aol'));
setConfigItem(CONFIG_reg_gender, (int)readPostVar('gender'));
setConfigItem(CONFIG_reg_birthday, (int)readPostVar('birthday'));
setConfigItem(CONFIG_reg_husbandwife, (int)readPostVar('husbandwife'));
setConfigItem(CONFIG_reg_children, (int)readPostVar('children'));
setConfigItem(CONFIG_reg_trainer, (int)readPostVar('trainer'));
setConfigItem(CONFIG_reg_photo, (int)readPostVar('photo'));
setConfigItem(CONFIG_reg_company, (int)readPostVar('company'));
setConfigItem(CONFIG_reg_cposition, (int)readPostVar('cposition'));
setConfigItem(CONFIG_reg_department, (int)readPostVar('department'));
setConfigItem(CONFIG_reg_coffice, (int)readPostVar('coffice'));
setConfigItem(CONFIG_reg_caddress, (int)readPostVar('caddress'));
setConfigItem(CONFIG_reg_ccity, (int)readPostVar('ccity'));
setConfigItem(CONFIG_reg_cstate, (int)readPostVar('cstate'));
setConfigItem(CONFIG_reg_czip, (int)readPostVar('czip'));
setConfigItem(CONFIG_reg_ccountry, (int)readPostVar('ccountry'));
setConfigItem(CONFIG_reg_cphone, (int)readPostVar('cphone'));
setConfigItem(CONFIG_reg_cfax, (int)readPostVar('cfax'));
setConfigItem(CONFIG_reg_cmobile, (int)readPostVar('cmobile'));
setConfigItem(CONFIG_reg_cpager, (int)readPostVar('cpager'));
setConfigItem(CONFIG_reg_cipphone, (int)readPostVar('cipphone'));
setConfigItem(CONFIG_reg_cwebpage, (int)readPostVar('cwebpage'));
setConfigItem(CONFIG_reg_cphoto, (int)readPostVar('cphoto'));
setConfigItem(CONFIG_reg_userfield1, (int)readPostVar('userfield1'));
setConfigItem(CONFIG_reg_caption_userfield1, readPostVar('caption_userfield1'));
setConfigItem(CONFIG_reg_type_userfield1, readPostVar('type_userfield1'));
setConfigItem(CONFIG_reg_values_userfield1, readPostVar('values_userfield1'));
setConfigItem(CONFIG_reg_userfield2, (int)readPostVar('userfield2'));
setConfigItem(CONFIG_reg_caption_userfield2, readPostVar('caption_userfield2'));
setConfigItem(CONFIG_reg_type_userfield2, readPostVar('type_userfield2'));
setConfigItem(CONFIG_reg_values_userfield2, readPostVar('values_userfield2'));
setConfigItem(CONFIG_reg_userfield3, (int)readPostVar('userfield3'));
setConfigItem(CONFIG_reg_caption_userfield3, readPostVar('caption_userfield3'));
setConfigItem(CONFIG_reg_type_userfield3, readPostVar('type_userfield3'));
setConfigItem(CONFIG_reg_values_userfield3, readPostVar('values_userfield3'));
setConfigItem(CONFIG_reg_userfield4, (int)readPostVar('userfield4'));
setConfigItem(CONFIG_reg_caption_userfield4, readPostVar('caption_userfield4'));
setConfigItem(CONFIG_reg_type_userfield4, readPostVar('type_userfield4'));
setConfigItem(CONFIG_reg_values_userfield4, readPostVar('values_userfield4'));
setConfigItem(CONFIG_reg_userfield5, (int)readPostVar('userfield5'));
setConfigItem(CONFIG_reg_caption_userfield5, readPostVar('caption_userfield5'));
setConfigItem(CONFIG_reg_type_userfield5, readPostVar('type_userfield5'));
setConfigItem(CONFIG_reg_values_userfield5, readPostVar('values_userfield5'));
setConfigItem(CONFIG_reg_userfield6, (int)readPostVar('userfield6'));
setConfigItem(CONFIG_reg_caption_userfield6, readPostVar('caption_userfield6'));
setConfigItem(CONFIG_reg_type_userfield6, readPostVar('type_userfield6'));
setConfigItem(CONFIG_reg_values_userfield6, readPostVar('values_userfield6'));
setConfigItem(CONFIG_reg_userfield7, (int)readPostVar('userfield7'));
setConfigItem(CONFIG_reg_caption_userfield7, readPostVar('caption_userfield7'));
setConfigItem(CONFIG_reg_type_userfield7, readPostVar('type_userfield7'));
setConfigItem(CONFIG_reg_values_userfield7, readPostVar('values_userfield7'));
setConfigItem(CONFIG_reg_userfield8, (int)readPostVar('userfield8'));
setConfigItem(CONFIG_reg_caption_userfield8, readPostVar('caption_userfield8'));
setConfigItem(CONFIG_reg_type_userfield8, readPostVar('type_userfield8'));
setConfigItem(CONFIG_reg_values_userfield8, readPostVar('values_userfield8'));
setConfigItem(CONFIG_reg_userfield9, (int)readPostVar('userfield9'));
setConfigItem(CONFIG_reg_caption_userfield9, readPostVar('caption_userfield9'));
setConfigItem(CONFIG_reg_type_userfield9, readPostVar('type_userfield9'));
setConfigItem(CONFIG_reg_values_userfield9, readPostVar('values_userfield9'));
setConfigItem(CONFIG_reg_userfield10, (int)readPostVar('userfield10'));
setConfigItem(CONFIG_reg_caption_userfield10, readPostVar('caption_userfield10'));
setConfigItem(CONFIG_reg_type_userfield10, readPostVar('type_userfield10'));
setConfigItem(CONFIG_reg_values_userfield10, readPostVar('values_userfield10'));
gotoLocation('config.php'.getURLAddon('', array('action')));
?>